apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert --out all-k8s-files.yml
      kompose.version: 1.17.0 (a74acad)
    creationTimestamp: null
    labels:
      io.kompose.service: kafka
    name: kafka
  spec:
    ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
    selector:
      io.kompose.service: kafka
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert --out all-k8s-files.yml
      kompose.version: 1.17.0 (a74acad)
    creationTimestamp: null
    labels:
      io.kompose.service: scylla
    name: scylla
  spec:
    ports:
    - name: "9042"
      port: 9042
      targetPort: 9042
    selector:
      io.kompose.service: scylla
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert --out all-k8s-files.yml
      kompose.version: 1.17.0 (a74acad)
    creationTimestamp: null
    labels:
      io.kompose.service: zookeeper
    name: zookeeper
  spec:
    ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
    selector:
      io.kompose.service: zookeeper
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: kafka
    name: kafka
  spec:
    containers:
    - env:
      - name: KAFKA_ADVERTISED_HOST_NAME
        value: 192.168.0.62
      - name: KAFKA_ZOOKEEPER_CONNECT
        value: zookeeper:2181
      image: wurstmeister/kafka
      name: kafka
      ports:
      - containerPort: 9092
      resources: {}
      volumeMounts:
      - mountPath: /var/run/docker.sock
        name: kafka-claim0
    restartPolicy: OnFailure
    volumes:
    - name: kafka-claim0
      persistentVolumeClaim:
        claimName: kafka-claim0
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: kafka-claim0
    name: kafka-claim0
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: scylla
    name: scylla
  spec:
    containers:
    - args:
      - --broadcast-address
      - 127.0.0.1
      - --broadcast-rpc-address
      - 127.0.0.1
      image: scylladb/scylla
      name: scylla
      ports:
      - containerPort: 9042
      resources: {}
    restartPolicy: OnFailure
  status: {}
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: zookeeper
    name: zookeeper
  spec:
    containers:
    - image: wurstmeister/zookeeper
      name: zookeeper
      ports:
      - containerPort: 2181
      resources: {}
    restartPolicy: OnFailure
  status: {}
kind: List
metadata: {}

