version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: on-failure
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.62
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
  scylla:
    image: scylladb/scylla
    ports:
      - "9042:9042"
    command: "--broadcast-address 127.0.0.1 --broadcast-rpc-address 127.0.0.1"
    restart: on-failure
#  java:
#    build:
#      context: .
#      dockerfile: java.dockerfile
#    ports:
#      - "5000:5000"
#    depends_on:
#      - zookeeper
#      - kafka
#      - scylla
#    restart: on-failure

#version: '3.7'
#services:
#  kafka:
#    build:
#      context: .
#      dockerfile: kafka.dockerfile
#    depends_on:
#      - scylla
#    ports:
#      - "29092:9092"
#    restart: on-failure
#  scylla:
#    image: scylladb/scylla
#    ports:
#      - "2409:9042"
#    command: "--broadcast-address 127.0.0.1 --broadcast-rpc-address 127.0.0.1"
#    restart: on-failure
#  java:
#    build:
#      context: .
#      dockerfile: java.dockerfile
#    ports:
#      - "5005:5005"
#    depends_on:
#      - scylla
#      - kafka
