apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  containers:
  - image: wurstmeister/zookeeper
    name: zookeeper
    ports:
    - containerPort: 2181
    resources: {}
  restartPolicy: OnFailure
status: {}
